[destination.postgres.credentials]
database = "postgres"
username = "postgres"
password = "mysecretpassword"
host = "localhost"
port = 5432

[destination.clickhouse]
dataset_table_separator = "___"
table_engine_type = "merge_tree"
dataset_sentinel_table_name = "dlt_sentinel_table"

[destination.clickhouse.credentials]
database = "my_database"
password = "password"
username = "username"
host = "localhost"
port = 9000
http_port = 8123
secure = 0